name: monadoc
version: 0.0.0

category: Documentation
description: Monadoc provides better Haskell documentation.
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
synopsis: Better Haskell documentation.

dependencies:
  - aeson == 1.2.3.0
  - base == 4.10.1.0
  - bytestring == 0.10.8.2
  - Cabal == 2.0.1.0
  - http-types == 0.11
  - text == 1.2.2.2
  - transformers == 0.5.2.0
  - wai == 3.2.1.1
  - wai-extra == 3.0.20.2
  - warp == 3.2.13
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

library:
  source-dirs: library

executable:
  dependencies: monadoc
  ghc-options:
    - -rtsopts
    - -threaded
  main: Main.hs
  source-dirs: executables
