# This should be using the nightly-2017-12-09 resolver, but there's a problem
# with Stack 1.6.1. I can't downgrade to Stack < 1.6.1 because it doesn't work
# with GHC >= 8.2. And I can't use GHC < 8.2 because I don't want to :)
# https://github.com/commercialhaskell/stack/issues/3631
# https://github.com/haskell-infra/hackage-trustees/issues/120
resolver: ghc-8.2.2

extra-deps:
  - appar-0.1.4
  - async-2.1.1.1
  - attoparsec-0.13.2.0
  - auto-update-0.1.4
  - blaze-builder-0.4.0.2
  - byteorder-1.0.4
  - bytestring-builder-0.10.8.1.0
  - case-insensitive-1.2.0.10
  - conduit-1.2.12.1
  - conduit-extra-1.1.17
  - exceptions-0.8.3
  - hashable-1.2.6.1
  - http-date-0.0.6.1
  - http-types-0.11
  - http2-1.6.3
  - integer-logarithms-1.0.2
  - iproute-1.7.1
  - lifted-base-0.2.3.11
  - mmorph-1.1.0
  - monad-control-1.0.2.2
  - mtl-2.2.1
  - network-2.6.3.2
  - primitive-0.6.2.0
  - psqueues-0.2.4.0
  - random-1.1
  - resourcet-1.1.10
  - scientific-0.3.5.2
  - simple-sendfile-0.2.25
  - stm-2.4.4.1
  - streaming-commons-0.1.18
  - text-1.2.2.2
  - transformers-base-0.4.4
  - transformers-compat-0.5.1.4
  - unix-compat-0.5.0.1
  - unliftio-core-0.1.0.0
  - unordered-containers-0.2.8.0
  - vault-0.3.0.7
  - wai-3.2.1.1
  - warp-3.2.13
  - word8-0.1.3
  - zlib-0.6.1.2
