# This should be using the nightly-2017-12-09 resolver, but there's a problem
# with Stack 1.6.1. I can't downgrade to Stack < 1.6.1 because it doesn't work
# with GHC >= 8.2. And I can't use GHC < 8.2 because I don't want to :)
# https://github.com/commercialhaskell/stack/issues/3631
# https://github.com/haskell-infra/hackage-trustees/issues/120
# https://github.com/fpco/stackage/issues/3092
resolver: ghc-8.2.2

extra-deps:
  - adjunctions-4.3
  - aeson-1.2.3.0
  - ansi-terminal-0.7.1.1
  - appar-0.1.4
  - asn1-encoding-0.9.5
  - asn1-parse-0.9.4
  - asn1-types-0.3.2
  - async-2.1.1.1
  - attoparsec-0.13.2.0
  - auto-update-0.1.4
  - base-compat-0.9.3
  - base-orphans-0.6
  - base64-bytestring-1.0.0.1
  - basement-0.0.4
  - bifunctors-5.5
  - blaze-builder-0.4.0.2
  - blaze-html-0.9.0.1
  - blaze-markup-0.8.0.0
  - byteable-0.1.1
  - byteorder-1.0.4
  - bytestring-builder-0.10.8.1.0
  - Cabal-2.0.1.1
  - cabal-doctest-1.0.4
  - call-stack-0.1.0
  - case-insensitive-1.2.0.10
  - cereal-0.5.4.0
  - colour-2.3.4
  - comonad-5.0.2
  - conduit-1.2.12.1
  - conduit-extra-1.1.17
  - connection-0.2.8
  - contravariant-1.4
  - cookie-0.4.3
  - cryptonite-0.24
  - data-default-class-0.1.2.0
  - distributive-0.5.3
  - dlist-0.8.0.3
  - easy-file-0.2.1
  - exceptions-0.8.3
  - fail-4.9.0.0
  - fast-logger-2.4.10
  - foundation-0.0.17
  - free-4.12.4
  - hashable-1.2.6.1
  - hourglass-0.2.10
  - http-client-0.5.7.1
  - http-client-tls-0.3.5.1
  - http-date-0.0.6.1
  - http-types-0.11
  - http2-1.6.3
  - integer-logarithms-1.0.2
  - iproute-1.7.1
  - kan-extensions-5.0.2
  - lens-4.15.4
  - lifted-base-0.2.3.11
  - memory-0.14.10
  - mime-types-0.1.0.7
  - mmorph-1.1.0
  - monad-control-1.0.2.2
  - mtl-2.2.1
  - network-2.6.3.2
  - network-uri-2.6.1.0
  - old-locale-1.0.0.7
  - parallel-3.2.1.1
  - parsec-3.1.11
  - pem-0.2.2
  - prelude-extras-0.4.0.3
  - primitive-0.6.2.0
  - profunctors-5.2.1
  - psqueues-0.2.4.0
  - random-1.1
  - reflection-2.1.2
  - resourcet-1.1.10
  - safe-0.3.15
  - scientific-0.3.5.2
  - semigroupoids-5.2.1
  - semigroups-0.18.3
  - simple-sendfile-0.2.25
  - socks-0.5.5
  - StateVar-1.1.0.4
  - stm-2.4.4.1
  - streaming-commons-0.1.18
  - stringsearch-0.3.6.6
  - tagged-0.8.5
  - text-1.2.2.2
  - th-abstraction-0.2.6.0
  - time-locale-compat-0.1.1.3
  - tls-1.4.0
  - transformers-0.5.5.0
  - transformers-base-0.4.4
  - transformers-compat-0.5.1.4
  - unix-compat-0.5.0.1
  - unliftio-core-0.1.0.0
  - unordered-containers-0.2.8.0
  - uuid-types-1.0.3
  - vault-0.3.0.7
  - vector-0.12.0.1
  - void-0.7.2
  - wai-3.2.1.1
  - wai-extra-3.0.20.2
  - wai-logger-2.3.0
  - warp-3.2.13
  - word8-0.1.3
  - x509-1.7.2
  - x509-store-1.6.5
  - x509-system-1.6.6
  - x509-validation-1.6.9
  - xml-conduit-1.7.0
  - xml-lens-0.1.6.3
  - xml-types-0.3.6
  - zlib-0.6.1.2

flags:
  time-locale-compat:
    old-locale: false
